Nike/Nike/Models/Blocks/HeaderBlock.cs
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.DataAnnotations;
using EPiServer.SpecializedProperties;
using System.ComponentModel.DataAnnotations;

namespace Nike.Models.Blocks
{
    [ContentType(DisplayName = "HeaderBlock", GUID = "9c7f3fa9-950a-4ad4-8501-fd340ade4b85", Description = "")]
    public class HeaderBlock : BlockData
    {
        [CultureSpecific]
        [Display(
           Name = "Categories",
           Description = "Add links to category pages, these would be displayed on the navbar within header",
           GroupName = SystemTabNames.Content,
           Order = 1)]
        public virtual LinkItemCollection Categories { get; set; }
    }
}

Nike/Nike/Controllers/HeaderBlockController.cs
using EPiServer.Web.Mvc;
using Nike.Models.Blocks;
using System.Web.Mvc;

namespace Nike.Controllers
{
    public class HeaderBlockController : BlockController<HeaderBlock>
    {
        public override ActionResult Index(HeaderBlock currentBlock)
        {
            return PartialView(currentBlock);
        }
    }
}

Nike/Nike/Controllers/MiniCartController.cs
using Nike.Models.ViewModels;
using Nike.Service.Services;
using System.Web.Mvc;

namespace Nike.Controllers
{
    public class MiniCartController : Controller
    {
        private CartService cartService;
        private GeneralService generalService;

        public MiniCartController()
        {
            generalService = new GeneralService();
            cartService = new CartService();
        }

        public ActionResult Index()
        {
            return PartialView("_MiniCart", new MiniCartViewModel(cartService.GetTotalNumberOfItemsInCart(), cartService.GetTotalPrice(), generalService.GetCurrentUserUsername()));
        }
    }
}

Nike/Nike/Views/HeaderBlock/Index.cshtml
@using EPiServer.Core
@using EPiServer.Web.Mvc.Html
@model Nike.Models.Blocks.HeaderBlock

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-12">
            <nav class="navbar navbar-default navbar-expand-md  ">
                <div class="container-fluid">
                    <div class="navbar-header lineh width-control">
                        <a href="/">
                            <img id="desktop-logo-only" src="~/images/Capture.PNG" class="icon_logo" />
                            <img id="mobile-logo-only" src="~/images/capture2.PNG" class="icon_logo2" />
                        </a>

                        <button type="button" class="navbar-toggle collapsed padd floating_right" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                                aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>

                        </button>
                        <span id="mobile-mini-cart" style="display: none"> @{Html.RenderAction("Index", "MiniCart");} </span>
                    </div>
                    <span id="desktop-mini-cart"> @{Html.RenderAction("Index", "MiniCart");} </span>
                    <div class="collapse navbar-collapse w-100 order-3 dual-collapse2 menu" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav ml-auto text-designer caps-lock centered-with-padding">

                            @{
                                int countRestrict = 4;
                                if (Model.Categories != null)
                                {
                                    foreach (var category in Model.Categories)
                                    {
                                        if (countRestrict > 0)
                                        {
                                            <li><a class="menu" href="@Url.ContentUrl(category.Href)" target="@category.Target">@category.Text</a></li>
                                        }
                                        countRestrict--;
                                    }
                                }
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </div>

    </div>
</div>