Nike/Nike/Models/Pages/ShoppingCartPage.cs
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.DataAnnotations;
using System.ComponentModel.DataAnnotations;

namespace Nike.Models.Pages
{
    [ContentType(DisplayName = "ShoppingCartPage", GUID = "2f4b93ab-9859-4be0-88ca-a1396f2ea14b", Description = "")]
    public class ShoppingCartPage : PageData
    {

        [CultureSpecific]
        [Display(
            Name = "Shopping Cart Title",
            Description = "",
            GroupName = SystemTabNames.Content,
            Order = 1)]
        public virtual XhtmlString ShoppingCartTitle { get; set; }

        [CultureSpecific]
        [Display(
              Name = "Cart Summary Title",
              Description = "",
              GroupName = SystemTabNames.Content,
              Order = 2)]
        public virtual XhtmlString CartSummaryTitle { get; set; }

        [CultureSpecific]
        [Display(
          Name = "Shopping Page Empty Text",
          Description = "",
          GroupName = SystemTabNames.Content,
          Order = 3)]
        public virtual XhtmlString TextWhenEmpty { get; set; }

    }
}

Nike/Nike/Controllers/CartSummaryTotalController.cs
using Nike.Models.ViewModels;
using Nike.Service.Services;
using System.Web.Mvc;

namespace Nike.Controllers
{
    public class CartSummaryTotalController : Controller
    {
        private CartService cartService;

        public CartSummaryTotalController()
        {
            cartService = new CartService();
        }

        // GET: CartSummaryTotal
        public ActionResult Index()
        {
            return PartialView("_CartSummary", new CartSummaryTotalViewModel(cartService.GetTotalPrice()));
        }
    }
}

Nike/Nike/Controllers/ShoppingCartItemListController.cs
using Nike.Helpers;
using Nike.Models.ViewModels.ShoppingCartViewModel;
using Nike.Service.Services;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Nike.Controllers
{
    public class ShoppingCartItemListController : Controller
    {
        private CartService cartService;

        public ShoppingCartItemListController()
        {
            cartService = new CartService();
        }

        public ActionResult ShoppingListView() {
            List<ShoppingCartItemViewModel> shoppingCartItems = cartService.GetAllShoppingCartItems();
            return PartialView("_ShoppingCartItemList", new ShoppingCartItemListViewModel(shoppingCartItems));
        }

        public JsonResult RemoveItem(string skuCode)
        {
            cartService.RemoveFromCart(skuCode);
            return Json(new { Code = skuCode, Price = GetTotalPrice() });
        }


        public JsonResult GetTotalPriceCartSummary()
        {
            return Json(new { TotalPrice = GetTotalPrice() });
        }

        public JsonResult UpdateItemQuantity(string skuCode, string quantity)
        {
            cartService.UpdateQuantity(skuCode, Decimal.Parse(quantity));
            return Json(new { Quantity = Decimal.Parse(quantity), Price = cartService.GetPriceForItem(skuCode), TotalPrice = GetTotalPrice()});
        }

        public decimal GetTotalPrice()
        {
            return cartService.GetTotalPrice();
        }
        

    }
}

Nike/Nike/Controllers/ShoppingCartPageController.cs
using EPiServer.Web.Mvc;
using Nike.Models.Pages;
using System.Web.Mvc;

namespace Nike.Controllers
{
    public class ShoppingCartPageController : PageController<ShoppingCartPage>
    {
   
        public ActionResult Index(ShoppingCartPage currentPage)
        {
            return View(currentPage);
        }
    }
}

Nike/Nike/Views/ShoppingCartPage/Index.cshtml
@model Nike.Models.Pages.ShoppingCartPage

<div class="container">
    <div class="row">
        <div class="col-xs-12 shopping-cart-title">
            @Html.PropertyFor(m => m.ShoppingCartTitle)
            <hr class="line" />
        </div>
    </div>
    <div id="when-cart-is-empty" class="hidden">
        <div>
            <div class="row image-box">
                <div class="image-box-image">
                    <img id="image-when-empty" src="~/images/cart/cart.png" class="image-cart-empty" />
                    <div id="text-when-empty" class="empty-cart-text">
                        @Html.Raw(Model.TextWhenEmpty)
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div>
        @{
            Html.RenderAction("ShoppingListView", "ShoppingCartItemList");
        }
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <br /><br />
            <div id="hidden-when-empty">
                <div class="cart-summary-title">@Html.PropertyFor(m => m.CartSummaryTitle)</div>
                <div class="capsule-cart-summary">
                    @{
                        Html.RenderAction("Index", "CartSummaryTotal");
                    }
                </div>
            </div>
        </div>
    </div>

</div>

<br />
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <button id="keepshopping" onclick="window.location.href='../'" name="keepshopping" class="keepshopping-button">
                <span class="glyphicon glyphicon-chevron-left" style="padding-right:12%"></span>
                KEEP SHOPPING
            </button>
        </div>
    </div>
</div>