Nike/Nike/Models/ViewModels/AuthenticationViewModels/LoginViewModel.cs
using Nike.Validators;
using System.ComponentModel.DataAnnotations;

namespace Nike.Models.ViewModels
{
    public class LoginViewModel
    {
        [CustomLoginEmailValidator]
        [Required(ErrorMessage = "Please input the Email Address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please input the Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public string IncompatibleFieldsError { get; set; }

    }
}

Nike/Nike/Models/ViewModels/AuthenticationViewModels/RegisterViewModel.cs
using Nike.Validators;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Nike.Models.ViewModels
{
    public class RegisterViewModel
    {
        [MaxLength(25)]
        [Required(ErrorMessage = "Please input the First Name")]
        public string FirstName { get; set; }

        [MaxLength(25)]
        [Required(ErrorMessage = "Please input the Last Name")]
        public string LastName { get; set; }
        
        [CustomEmailValidator]
        [Required(ErrorMessage = "Please input the Email Address")]
        public string Email { get; set; }

        [CustomPhoneNumberValidator]
        [Required(ErrorMessage = "Please input the Phone Number")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "Please select a gender")]
        public string Gender { get; set; }

       // [Required(ErrorMessage = "Please select a state")]
        public string SelectedState { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please input the Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please confirm your Password")]
        [System.ComponentModel.DataAnnotations.Compare("Password")]
        public string ConfirmPassword { get; set; }

        public IEnumerable<string> StateList = new List<string>()
        {
            "Romania",
            "Netherlands",
            "France"
        };
    }
} 

Nike/Nike/Models/ViewModels/ShoppingCartViewModel/MiniCartViewModel.cs
namespace Nike.Models.ViewModels
{
    public class MiniCartViewModel
    {
        public decimal NumberOfItems { get; set; }
        public decimal TotalPrice { get; set; }
        public string Username { get; set; }


        public MiniCartViewModel(decimal NumberOfItems, decimal TotalPrice, string Username)
        {
            this.NumberOfItems = NumberOfItems;
            this.TotalPrice = TotalPrice;
            this.Username = Username;
        }
    }
}

Nike/Nike/Models/ViewModels/ShoppingCartViewModel/ShoppingCartItemListViewModel.cs
using Nike.Helpers;
using System.Collections.Generic;

namespace Nike.Models.ViewModels.ShoppingCartViewModel
{
    public class ShoppingCartItemListViewModel
    {
        public List<ShoppingCartItemViewModel> ShoppingCartItemList { get; set; }

        public ShoppingCartItemListViewModel() { }

        public ShoppingCartItemListViewModel(List<ShoppingCartItemViewModel> shoppingCartItemList)
        {
            ShoppingCartItemList = shoppingCartItemList;
        }
    }
}

Nike/Nike/Controllers/LayoutController.cs
using Nike.Models;
using Nike.Models.ViewModels;
using Nike.Service.Services;
using System.Web.Mvc;

namespace Nike.Controllers
{
    public class LayoutController : Controller
    {
        private CartService cartService;
        private GeneralService generalService;

        public LayoutController()
        {
            cartService = new CartService();
            generalService = new GeneralService();
        }

        public ActionResult NavBar()
        {
            return PartialView("_NavBar", new MenuViewModel { VisiblePages = generalService.GetVisiblePages() });
        }

        public JsonResult MiniCart()
        {
            cartService = new CartService();
            return Json(new MiniCartViewModel(cartService.GetTotalNumberOfItemsInCart(), cartService.GetTotalPrice(), generalService.GetCurrentUserUsername()));
        }

        public ActionResult Footer()
        {
            return PartialView("~/Views/FooterBlock/Index.cshtml", generalService.GetPageFooter());
        }

        public ActionResult Header()
        {
            return PartialView("~/Views/HeaderBlock/Index.cshtml", generalService.GetPageHeader());
        }
        
        public JsonResult RedirectToShoppingCartPage()
        {
            return Json(new { url = generalService.GetShoppingCartPage().LinkURL });
        }

        public JsonResult RedirectToLoginPage()
        {
            return Json(new { url = generalService.GetLogInPage().LinkURL });
        }
    }
}

Nike/Nike/Controllers/MiniCartController.cs
using Nike.Models.ViewModels;
using Nike.Service.Services;
using System.Web.Mvc;

namespace Nike.Controllers
{
    public class MiniCartController : Controller
    {
        private CartService cartService;
        private GeneralService generalService;

        public MiniCartController()
        {
            generalService = new GeneralService();
            cartService = new CartService();
        }

        public ActionResult Index()
        {
            return PartialView("_MiniCart", new MiniCartViewModel(cartService.GetTotalNumberOfItemsInCart(), cartService.GetTotalPrice(), generalService.GetCurrentUserUsername()));
        }
    }
}

Nike/Nike/Controllers/RegisterAndLogInPageController.cs
using EPiServer.Web.Mvc;
using Nike.Helpers;
using Nike.Models.Pages;
using Nike.Models.ViewModels;
using Nike.Service.Services;
using System.Web.Mvc;
using System.Web.Security;

namespace Nike.Controllers
{
    public class RegisterAndLogInPageController : PageController<RegisterAndLogInPage>
    {
        private LoginService loginService;
        private BreadcrumbService breadcrumbService;

        public RegisterAndLogInPageController()
        {
            loginService = new LoginService();
            breadcrumbService = new BreadcrumbService();
        }

        public ActionResult Index(RegisterAndLogInPage currentPage)
        {
            return (loginService.IsAuthenticated()) ? (ActionResult)Redirect(breadcrumbService.GetStartPageUrl()) : View(RegisterLoginViewModelFactory.Create(currentPage));
        }

        public ActionResult _Register(RegisterViewModel registerViewModel)
        {
            return PartialView("~/Views/Shared/_Register.cshtml", registerViewModel);
        }

        public ActionResult _Login(LoginViewModel loginViewModel)
        {
            return PartialView("~/Views/Shared/_Login.cshtml", loginViewModel);
        }

        [HttpPost]
        public ActionResult Register([Bind(Include = "FirstName,LastName,PhoneNumber,Email,Gender,State,Password,ConfirmPassword")] RegisterViewModel registerViewModel)
        {
            if (ModelState.IsValid)
            {
                loginService.RegisterUser(registerViewModel);
                loginService.AuthenticateUser(registerViewModel.Email);
                return Json(new { redirectTo = breadcrumbService.GetStartPageUrl() });
            }
            else
            {
                return PartialView("~/Views/Shared/_Register.cshtml", registerViewModel);
            }
        }

        [HttpPost]
        public ActionResult Login([Bind(Include = "Email,Password")] LoginViewModel loginViewModel)
        {
            if (ModelState.IsValid)
            {
                if (Membership.ValidateUser(loginViewModel.Email, loginViewModel.Password))
                {
                    loginService.AuthenticateUser(loginViewModel.Email);
                    return Json(new { redirectTo = breadcrumbService.GetStartPageUrl() });
                }
                else
                {
                    loginViewModel.IncompatibleFieldsError = "Invalid password for the provided email";
                }
            }
            return PartialView("~/Views/Shared/_Login.cshtml", loginViewModel);
        }

        [HttpPost]
        public void SignOut()
        {
            loginService.LogOutUser(HttpContext.Session);
        }

    }
}

Nike/Nike/Controllers/ShoppingCartItemListController.cs
using Nike.Helpers;
using Nike.Models.ViewModels.ShoppingCartViewModel;
using Nike.Service.Services;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Nike.Controllers
{
    public class ShoppingCartItemListController : Controller
    {
        private CartService cartService;

        public ShoppingCartItemListController()
        {
            cartService = new CartService();
        }

        public ActionResult ShoppingListView() {
            List<ShoppingCartItemViewModel> shoppingCartItems = cartService.GetAllShoppingCartItems();
            return PartialView("_ShoppingCartItemList", new ShoppingCartItemListViewModel(shoppingCartItems));
        }

        public JsonResult RemoveItem(string skuCode)
        {
            cartService.RemoveFromCart(skuCode);
            return Json(new { Code = skuCode, Price = GetTotalPrice() });
        }


        public JsonResult GetTotalPriceCartSummary()
        {
            return Json(new { TotalPrice = GetTotalPrice() });
        }

        public JsonResult UpdateItemQuantity(string skuCode, string quantity)
        {
            cartService.UpdateQuantity(skuCode, Decimal.Parse(quantity));
            return Json(new { Quantity = Decimal.Parse(quantity), Price = cartService.GetPriceForItem(skuCode), TotalPrice = GetTotalPrice()});
        }

        public decimal GetTotalPrice()
        {
            return cartService.GetTotalPrice();
        }
        

    }
}

Nike/Nike/Views/Shared/_CartSummary.cshtml
@model Nike.Models.ViewModels.CartSummaryTotalViewModel

<div class="total-title">
    Total: &nbsp; &nbsp;
    <p id="cart-summary-total-price" class="price-value">$@Model.TotalPrice.ToString("0.00")</p>
</div>

Nike/Nike/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Montserrat:100,300,400,700' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet'>

    @Styles.Render("~/bundles/layoutCSS")
    @Styles.Render("~/bundles/heroBlock")
    @Styles.Render("~/bundles/slickStyle")
    @Styles.Render("~/bundles/commerceCSS")
</head>
<body>
    <div class="wrapper">
        @{
            Html.RenderAction("Header", "Layout");
        }
        <br>
        <hr class="title-line" />
        <br />
        <div class="container">
            @RenderBody()
        </div>
    </div>
    <div class="big-footer">
        @{ Html.RenderAction("Footer", "Layout"); }

        <footer>
            <br />
            <p class="copyright">
                ©2018. All rights reserved.
            </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/common")
    @Scripts.Render("~/bundles/slickJS")

    @Styles.Render("~/bundles/commerceCSS")

    <script src="https://use.fontawesome.com/e6036bd41b.js"></script>

</body>
</html>

Nike/Nike/Views/Shared/_Login.cshtml
@model Nike.Models.ViewModels.LoginViewModel

<div id="login-form">
    @using (Ajax.BeginForm("Login", "RegisterAndLogInPage", new AjaxOptions { OnSuccess = "handleLoginSuccess" }))
    {
        @Html.ValidationSummary(true)
        <fieldset>

            <p class="mylabel"> Email </p>
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "input" } })
            <br />
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "errormessage" })

            <p class="mylabel"> Password </p>
            <div class="mylabel">
                @Html.PasswordFor(model => model.Password, new { @class = "input", placeholder = "Password" })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "errormessage" })
                <p id="custom-password-error" class="errormessage">@Model.IncompatibleFieldsError</p>
            </div>
            <p>
                <input type="submit" value="LOG IN" class="button" />

            </p>
        </fieldset>
    }
</div>

Nike/Nike/Views/Shared/_MiniCart.cshtml
@model Nike.Models.ViewModels.MiniCartViewModel

<div class="container-tooltip-2 target">
    <div class="pop-2 bottom fa fa-shopping-cart" data-placement="bottom" data-toggle="popover-2" data-container="body" data-html="true" href="#" id="shopping-cart-symbol">
        <div id="not"> <span id="itemNr" class="itemNr">@Model.NumberOfItems</span> </div>
    </div>

    &nbsp;&nbsp;&nbsp;&nbsp;
    <div id="popover-content-2" class="hide">
        <div class="row">
            <div class="col-xs-12 centered">
                <p class="unchangeable-cursor">Cart Total: <span id="totalprice" class="totalprice">$@Model.TotalPrice.ToString("0.00")</span></p>

                <button onclick="RedirectPage()" id="viewcart-btn" name="tooltip-button" class="tooltip-btn btn btn-sm btn-primary">
                    View Cart
                </button>
            </div>
        </div>
    </div>
</div>

<div class="container-tooltip target circle-name-container">

    <span id="visible-for-guest"> </span>
    <span class="pop bottom" data-placement="bottom" data-toggle="popover" data-container="body" data-html="true" href="#" id="loggeduser">

        <span class="fa-stack fa-lg name-circle">
            <span class="fa fa-circle fa-stack-2x"></span>
            @{
                if (Model.Username.Length != 0 && !Model.Username.Equals("GUEST"))
                {
                    <span class="fa fa-inverse fa-stack-1x unchangeable-cursor">@Model.Username.ToUpper()[0]</span>
                }
                else
                {
                    <span class="fa fa-inverse fa-stack-1x"><i class="fa fa-user" aria-hidden="true"></i></span>
                }

            }

        </span>

    </span>
    &nbsp;&nbsp;&nbsp;&nbsp;
    <div id="popover-content" class="hide">
        <div class="row">
            <div class="col-xs-12 centered">
                @{ if (Model.Username.Length != 0 && !Model.Username.Equals("GUEST"))
                    {
                        <p class="unchangeable-cursor">@Model.Username</p>
                        <hr class="nomargin-hr">
                        <p class="unchangeable-cursor"> Leaving already? <i class="fa fa-frown-o sad-face" aria-hidden="true"></i></p>
                        <button id="logout" name="tooltip-button" class="tooltip-btn btn btn-sm btn-primary">
                            Log Out
                        </button>
                    }
                    else
                    {
                        <p class="unchangeable-cursor">Guest</p>
                        <hr class="nomargin-hr">
                        <button id="register-login" name="tooltip-button" class="tooltip-btn btn btn-sm btn-primary">
                            Register / Log In
                        </button>
                    }

                }

            </div>
        </div>
    </div>
</div>

Nike/Nike/Views/Shared/_NavBar.cshtml
@model Nike.Models.MenuViewModel


@foreach (Tuple<string, string> page in Model.VisiblePages)
{
    <li>
        <a href="@page.Item1"> @page.Item2</a>

    </li>
}

Nike/Nike/Views/Shared/_Register.cshtml
@model Nike.Models.ViewModels.RegisterViewModel
<div id="register-form">
    @using (Ajax.BeginForm("Register", "RegisterAndLogInPage", new AjaxOptions { OnSuccess = "handleSuccess" }))
    {
        @Html.ValidationSummary(true)
    <fieldset>
        <br />

        <p class="mylabel"> First Name </p>
        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "input" } })
        <br />
        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "errormessage" })

        <br />
        <br />

        <p class="mylabel"> Last Name </p>

        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "input" } })
        <br />
        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "errormessage" })


        <br>
        <br />

        <p class="mylabel"> Phone Number </p>


        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "input" } })
        <br />
        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "errormessage" })


        <br>
        <br />

        <p class="mylabel"> Email </p>

        <div class="mylabel">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "input", id ="register-email"} })
            <br />
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "errormessage" })
        </div>

        <br />
        <p class="mylabel"> Gender </p>

        <span class="gender-label"> Male </span>
        @Html.RadioButtonFor(m => m.Gender, "Male", new { @id = "male", @htmlAttributes = new { @class = "radiobuttons" } })
        <span class="gender-label"> Female </span>
        @Html.RadioButtonFor(m => m.Gender, "Female", new { @id = "female", @htmlAttributes = new { @class = "radiobuttons", id = "female" } })
        <br />
        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "errormessage" })
        <br />
        <br />

        <dl>
            <dt> <span class="mylabel" style="font-weight: normal;"> State </span></dt>
            <dd>
                @Html.DropDownListFor(m => Model.SelectedState, new SelectList(Model.StateList), "Select state", new { @class = "input" })
            </dd>
        </dl>
        @*@Html.ValidationMessageFor(model => model.SelectedState, "", new { @class = "errormessage" })*@
        <br />
        <p class="mylabel"> Password </p>
        <div class="mylabel">
            @Html.PasswordFor(model => model.Password, new { @class = "input", placeholder = "Password", id = "register-password" })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "errormessage" })
        </div>

        <br>

        <p class="mylabel"> Confirm Password </p>
        <div class="mylabel">
            @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "input", placeholder = "Password" })
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "errormessage" })
        </div>
        <br />
        <p>
            <input type="submit" value="REGISTER" class="button" />

        </p>
    </fieldset>
    }
</div>

Nike/Nike/Views/Shared/_ShoppingCartItemList.cshtml
@model Nike.Models.ViewModels.ShoppingCartViewModel.ShoppingCartItemListViewModel
<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
    <br />
    <div id="item-list-count" data-model="@Json.Encode(Model.ShoppingCartItemList.Count)"></div>


    <div class="row ">
        <div id="shopping-cart-list-section">
            @{
                int idCounter = 1;
            }
            @foreach (var item in Model.ShoppingCartItemList)
            {<br id="br1-@item.SkuCode"> <br id="br2-@item.SkuCode">
                <div class="col-xs-12 col-sm-3 col-md-4 col-lg-3" id="@item.SkuCode">
                    @{
                        if (item.ImageUrl == "" || item.ImageUrl == null)
                        {
                            <img class="big-thumbnail" src="~/images/No_Image_Available.jpg" id="main" />
                        }
                        else
                        {
                            <img class="item-image" src="@item.ImageUrl" />
                        }
                    }


                    <button class="item-remove-button" data-id="@idCounter" name="item-remove-button">remove</button>
                    <input type="text" id="input-remove-@idCounter" name="input-remove-@idCounter" value="@item.SkuCode" style="display : none">
                </div>
                <div class="col-xs-12  col-sm-9 col-md-8 col-lg-9 border-bottom" id="desc-@item.SkuCode">
                    <div class="row ">
                        <br />
                        <div class="col-xs-6">
                            <div class="item-details item-title">@item.ProductName</div>
                            <div class="item-details">Size: &nbsp;@item.SelectedSize</div>
                            <div class="item-details">
                                Color: &nbsp;
                                <div class="tooltip-color">
                                    <img class="item-color-square" style="background-color: @item.SelectedColorCode" />
                                    <span class="tooltiptext">@item.SelectedColorName</span>
                                </div>
                            </div>
                            <a class="hidden" id="@("item-price" + idCounter)">@item.PriceOneItem</a>
                            <div class="item-details">
                                Quantity:  &nbsp;
                                <input type="number" min="1" step="1" class="quantity-box" style="display:inline;" onchange="return computeItemTotalPrice(@idCounter)" id="@("item-quantity" + idCounter)" value="@item.Quantity">
                                <div class="errormessage" id="@("errormessage" + idCounter)"></div>
                            </div>
                            <input type="text" id="quantity-changer-@idCounter" value="@item.SkuCode" style="display : none">
                        </div>
                        <div class="col-xs-6">
                            <div class="item-price">PRICE</div><br />
                            <div class="item-price price-value" id="@("item" + idCounter)">$@item.TotalPrice.ToString("0.00")</div>
                            @{
                                idCounter++;
                            }
                        </div>
                    </div>
                    <br />
                </div>
                <div class="row " id="row-@item.SkuCode"></div>
            }
        </div>
    </div>


</div>